# .github/workflows/sync-from-gitlab.yml
name: Sync from GitLab

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Pull from GitLab
        run: |
          git config --global user.email "eroscamaru@gmail.com"
          git config --global user.name "Eros Camacho Ruiz"

          # Add GitLab remote using the token securely
          git remote add gitlab https://${{ secrets.eroscamacho }}:${{ secrets.glpat-A49Ms_-DzACGhAWZe3JwEG86MQp1OjRtYmNkCw.01.1212j7rbw }}@gitlab.com/hwsec/hwsec_verilator/

          # Fetch and merge
          git fetch gitlab
          git merge gitlab/main --allow-unrelated-histories -m "Sync from GitLab"
          git push origin main
